default: &default
  adapter: mysql2
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  encoding: utf8
  reconnect: true
  pool: 5

development:
  <<: *default
  
test:
  <<: *default

production:
  <<: *default